version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: cet_mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: 'admin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - cet

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: cet_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - cet

  # Symfony apache project container
  www:
    build: docker/php
    container_name: cet_www
    ports:
      - "80:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - cet

networks:
  cet:

volumes:
  db-data: